### ISSUE TITLE
cfn arg with pointer to custom types throws exception

### ISSUE THREAD

**Issue by phronmophobic** [IGJoshua/coffi#3]
```c
typedef struct S1 {
    char c;
    void* p;
} S1;

extern void f1(S1* s){
    
}
```

```clojure
(defalias ::S1
  (layout/with-c-layout
   [::mem/struct
    [[:c ::mem/char]
     [:p ::mem/pointer]]]))

(defcfn
 f1
 ""
 "f1"
  [[:coffi.mem/pointer ::S1]]
 :coffi.mem/void)
;; Syntax error compiling at (*cider-repl workspace/clong:localhost:58963(clj)*:40:33).
Unable to resolve symbol: scope12651 in this context
```

It's likely that I'm doing something dumb here, but I thought I'd file an issue just in case.

Also, I saw the following notes in the readme:
> In cases where a pointer to some data is required to pass as an argument to a native function, but doesn't need to be read back in, the pointer primitive type can take a type argument.

I'm not actually sure what you mean by "doesn't need to be read back in".

**Comment by IGJoshua** [comment]
I'll work on fixing this, it's highly likely it's just a bug in one of my inline function definitions. Your definitions as written here should work without change once I introduce a fix.

As for the readme, what this means here is that the value being passed will be allocated, serialized into, the pointer passed to the native function, but once the function returns as you have no access to that pointer you would be unable to deserialize the value stored in that argument pointer, as might be required for a function that modifies its arguments (e.g. an out parameter).

**Comment by IGJoshua** [comment]
Fixed on develop
