### ISSUE TITLE
JDK19: ClassNotFoundException for jdk.incubator.foreign.Addressable

### ISSUE THREAD

**Issue by jackrusher** [IGJoshua/coffi#4]
This library looks for useful! Unfortunately, my first tests hit a wall right away. If I start the JVM with the `--add-modules=jdk.incubator.foreign` flag set, I get:
```
java.lang.module.FindException: Module jdk.incubator.foreign not found
```
... and if I remove that flag, I get an error telling me that it can't find the `jdk.incubator.foreign.Addressable` class.

This is on an aarch64 Mac/MacOS 12.6.1. My JDK info:
```
java -version
openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment Homebrew (build 19.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 19.0.1, mixed mode, sharing)
```

Anything I should try? Thanks in advance.

**Comment by jackrusher** [comment]
Ah, they've moved the classes to `java.lang.foreign.Addressable` in recent JDKs.

**Comment by IGJoshua** [comment]
Hey! Thanks for showing interest! I have JDK 19 support available on the develop branch, with updated usage instructions in the readme. Just ignore the version info on the readme and do a git dep against the latest develop sha.

I will be cutting a proper jdk 19 release in the near future, but it's perfectly functional in the mean time!
